<?php include "sides/mininavi_3.php"; ?>
	<!-- Content -->
	<h1>Bericht unseres ehemaligen Jahrespraktikanten Ali Gürler</h1>
	<br />
	<p>21.11.2001    <br /> In diesem kurzen Aufsatz berichte ich, wie ich an meinen Praktikumsplatz der Fachhochschule Gießen-Friedberg gekommen bin:</p>
	<p><img title="Prof. Dr. Meyer zu Bexten mit Ali Gürler und zwei Auszubildenden" style="margin-left: 10px; margin-bottom: 10px; float: right;" src="bliz/img/bilder/bericht-jahrespraktikant-ali-guerler.jpg" alt="Prof. Dr. Meyer zu Bexten mit Ali Gürler und zwei Auszubildenden" />Der Anfang war die Sendung "Lass' Dich überraschen". Dort hatte meine Verlobte, Manola Messing, hingeschrieben, um mich, als Überraschung, mit professioneller Hilfe, Auto fahren zu lassen. Im Februar 2001 schrieb das ZDF Manola an, weil man an diesem Vorschlag, mich Auto fahren zu lassen, interessiert zu sein schien. Dies wäre ja auch nichts außergewöhnliches, wäre ich nicht blind. Und mein größter Wunsch war es nun mal Auto zu fahren. Irgendwann kam dann eine Dame zu mir, die sich als Psychologin ausgab und die eine Arbeit ganz allgemein über Blinde und deren Lebensweise schrieb. Hierzu sollte ich nun interviewt werden. Da ich die Blindenstudienanstalt in Marburg besuchte, war das nichts ungewöhnliches, dass Psychologen der Philips Universität Marburg uns Blinde zu verschiedenen Themenbereichen unserer Blindheit befragen. Also führte die Dame mit mir ein sehr ausgiebiges Interview über meine Blindheit. Dabei waren so Fragen inbegriffen, wie: "Wie findest Du Dich auf Straßen zurecht?", usw.</p>
	<p>Manola lockte mich eines Morgens im Mai aus dem Bett, mit Argumenten wie: "Ich möchte mit Dir frühstücken, damit ich Kraft für den Tag habe", oder "Rasierst Du Dich für mich, damit ich von Dir einen Kuß haben kann, der nicht so kratzig ist?" Nach einiger Zeit hatte sie mich dann soweit, dass ich mich duschte, mich rasierte und mich eben für den Tag fertig machte. Manola sollte ich wohl deshalb morgens soviel Beistand leisten, weil sie von ihrer Firma eine Schulung für neu eingeführte Computersysteme erhalten solle. Das würde ja so anstrengend werden.</p>
	<p>Nachdem wir sehr sehr lange gefrühstückt hatten, machte sich Manola fertig, um ihre Schulung pünktlich wahrnehmen zu können. Mit einem letzten Kuss verabschiedeten wir uns voneinander. Daraufhin ging Manola weg. Eigentlich hatte ich vor, mich an diesem Tag mit meinem Computer zu beschäftigen und ihn wieder aufzupeppeln. Bei einer weiteren Tasse Kaffee klingelte es plötzlich an der Tür. Als ich die Tür öffnete, hörte ich es auf der Treppe knacken.</p>
	<p>Ein Mann begrüßte mich mit meinem Namen und stellte sich mir als Thomas Ohrner vor. Dieser Name war mir nicht wirklich geläufig. Seine Fernsehsendung "Lass' Dich überraschen" war mir auch nur vom Namen bekannt. "Glaubst Du mir denn, dass ich Thomas Ohrner bin?", fragte er mich, woraufhin ich ihm erwiderte, dass ich keinen Grund hätte, ihm nicht zu glauben. Ob ich eine Tasse Kaffee für ihn hätte, war die nächste Frage. Wie es der Zufall wollte, war noch genau eine Tasse Kaffee übrig. Als wir uns dann in die Küche setzten, fragte Thomas Ohrner mich, ob ich mir denken könne, warum er denn ausgerechnet mich besuche. Anfangs gelang es mir nicht, nachzuvollziehen, womit er mich überraschen könnte. Aber dann packte er ein Überraschungsei aus. Man merkte deutlich, dass das präpariert war, weil gleich die beiden Schokoladenhälften auseinanderfielen. Im Plastikei befand sich ein Spielzeugauto. Sofort wurde mir klar, was ich an jenem Tag tun durfte. Ich durfte, das war mein allergrößter Wunsch, Auto fahren!</p>
	<p>Also brachte mich das ZDF nach Olpe. Dort gibt es ein Gelände, auf welchem man ein Fahrsicherheitstraining absolvieren kann. Dort verlebte ich einen wunderschönen Tag. Ein großer Wunsch ging für mich in Erfüllung. Manola, die das ganze infiziert hatte, war ebenfalls mit ihrem Werk sehr zufrieden. Ich bedankte mich bei Manola für den schönen Tag.</p>
	<p>Das ganze Spektakel musste aber noch im Studio in Berlin aufgezeichnet werden. Für diesen Termin wurde der 04.09.2001 angesetzt. Also reisten wir, Manola und ich, nach Berlin. Ich ging davon aus, dass das, womit ich ja bereits überrascht wurde, nur noch in die laufende Sendung eingebaut werden würde. Aber es kam alles ganz anders: Als wir gekämmt, gebürstet und noch anders kameratauglich gemacht wurden, musste ich proben, mit einem Auto auf die Bühne zu fahren. Obendrein musste ich noch auf einer Linie so stehen bleiben, dass die Kameraperspektive genau eingehalten werden konnte. Manola sollte mir das Kommando geben, anzuhalten. Nach mehrmaligem Üben warteten wir wieder in der Garderobe. Auch die anderen Teilnehmer, die überrascht wurden, mussten sich Proben unterziehen, um entsprechend vor der Kamera aufzutreten.</p>
	<p>Dann kam der große Augenblick. Ich war der zweite Teilnehmer der Sendung. Als man mich in das Auto setzte, war ich sehr aufgeregt. Alleine die Frage, ob auch alles klappt, machte mir doch sehr zu schaffen. Manola saß neben mir auf dem Beifahrersitz. Sie gab mir das Kommando, loszufahren. So langsam ich konnte, fuhr ich an. Gleich musste ich mich darauf konzentrieren, Manolas Stoppkommando nicht zu verfehlen. Ich stand zwar nicht ganz genau auf der Linie, aber ich stand. Thomas Ohrner unterhielt sich mit mir. Er fragte mich, wie ich denn die Überraschung empfunden hätte, die Manola mir gemacht hatte. "Du hast ja nichts verlernt", merkte er an. Weiterhin fragte er mich nach meiner beruflichen Perspektive. Mein Traum ist es eine Ausbildung zum Fachinformatiker zu machen.</p>
	<p>An dieser Stelle muss ich ein Paar Dinge erklären, damit Sie in der Lage sind den Sachverhalt nachzuvollziehen: Ich bin nach der 12. Klasse von der Blindenstudienanstalt in Marburg abgegangen. Mir fehlte der praktische Teil, um die allgemeine Fachhochschulreife zu bekommen. Also musste ich mir entweder einen Ausbildungs- oder einen Praktikumsplatz suchen, um mir später die allgemeine Fachhochschulreife von der Blindenstudienanstalt ausstellen zu lassen. Zu diesem Zweck habe ich mehrere Bewerbungen geschrieben, auch an das Zentrum für Blinde und Sehbehinderte Studierende (BliZ) der Fachhochschule Gießen-Friedberg. Meine Ansprechpartnerin war Frau Prof. Dr. Meyer zu Bexten, die Leiterin des Blindenzentrums. Leider musste Frau Prof. Dr. Meyer zu Bexten meine Bewerbung ablehnen, da das BliZ keine Kosten für einen Betreuer, der mich ein- bis zweimal in der Woche betreuen würde, übernehmen konnte.</p>
	<p>Um wieder zum eigentlichen Geschehen der Sendung zurück zu kommen: Auf die Frage nach meiner beruflichen Zukunft, gab ich Herrn Ohrner zu verstehen, dass ich nach langem Probieren ein Vorstellungsgespräch mit einer Computerfirma auf die Beine stellen konnte. Daraufhin die Frage von ihm: "Wollen wir das Vorstellungsgespräch nicht gleich hier führen, Ali?" Jetzt begann es in mir zu brodeln, weil ich sehr verwirrt war. Ob er denn mit mir ein Vorstellungsgespräch führen wollte, fragte ich Thomas Ohrner. Dafür hätte er jemanden eingeladen, der qualifizierter wäre. "Und hier ist Frau Prof. Dr. Meyer zu Bexten!", erhob sich seine Stimme.</p>
	<p>Wie aus dem Nichts tauchte Frau Prof. Dr. Meyer zu Bexten auf. Vor dem Publikum teilte sie mir mit, dass es durch die Hilfe der <!--<a href="/bliz/" target="_blank">--> Gladebeckstiftung <!--</a>--> und <a href="http://www.aktion-mensch.de/" target="_blank">Aktion Mensch</a> möglich geworden sei, die Kosten eines Betreuers zu finanzieren. Der Praktikumsvertrag habe eine Gültigkeit von einem Jahr, er sei seitens der Fachhochschule Gießen/Friedberg unterzeichnet. Nur noch ich sei derjenige, der den Vertrag unterzeichnen müsse, um sofort als Praktikant beim Blindenzentrum der Fachhochschule Gießen/Friedberg anfangen zu können. Meine Gefühle, die ich während des Ablaufs hatte, kann ich nicht mit Worten wiedergeben. Für mich war klar, dass sich mir mit diesem Angebot ein großes Tor öffnete. Ebenso war mir klar, dass ich das Vorstellungsgespräch absagen würde, wenn ich zu Hause wäre. Im Übrigen war die Dame, die sich als Psychologin ausgab, die Redaktionsleiterin von der Sendung "Lass' Dich überraschen". Diese wollte für die Sendung Dinge von mir wissen, die sie für die Durchführung der Überraschung wissen musste.</p>
	<p>Am 10.09.2001 nahm ich meine Tätigkeit als Praktikant im Blindenzentrum der Fachhochschule Gießen/Friedberg auf. Es sind also schon zwei Monate, die ich hier bin. Natürlich habe ich mich am Anfang gefragt, mit welchen Menschen ich zusammentreffen würde. Eine gewisse Angst hatte ich davor, dass das Praktikum nicht meinen Vorstellungen entsprechend laufen würde. Diese Angst erwies sich später als unbegründet. Die Auszubildenden, mit denen ich zusammenarbeite, sind alle ausnahmslos sehr nett. Auch Frau Prof. Dr. Meyer zu Bexten und ich verstehen uns gut miteinander. Ein besonderer Dank sei an dieser Stelle ihr gewidmet. Hätte Frau Prof. Dr. Meyer zu Bexten mir diese Möglichkeit nicht eingeräumt, hätte ich nicht unmittelbar damit rechnen können, einen Praktikumsplatz zu bekommen.</p>
	<p>Vielen Dank, Frau Prof. Dr. Meyer zu Bexten!</p>
	<p>Meine E-Mail-Adresse hier in Gießen ist: <a href="javascript:// Diese E-Mail Adresse ist vor Spambots gesch&uuml;tzt."><span class="cloaked_email" id="ep_78222f02"><span data-ep-b75fa="n.&#100;&#101;" data-ep-ad684="&#65;&#108;i.&#71;"><span data-ep-b75fa="&#105;e&#115;se" data-ep-ad684="&#117;&#101;r&#108;&#101;"><span data-ep-ad684="&#114;&#64;&#109;&#110;i" data-ep-b75fa=".&#102;h&#45;&#103;"></span></span></span></span><span class="cloaked_email" id="ep_6d829136" style="display:none;"><span data-ep-b75fa="n&#46;d&#101;" data-ep-ad684="Al&#105;.&#71;"><span data-ep-b75fa="i&#101;s&#115;&#101;" data-ep-ad684="&#117;e&#114;le"><span data-ep-b75fa="&#46;&#102;&#104;&#45;g" data-ep-ad684="r&#64;&#109;ni"></span></span></span></span></a><script type="text/javascript">emailProtector.addCloakedMailto("ep_6d829136", 1);</script></p>
	<!-- ContentEnde -->
<?php include "sides/fachbereich/archivsidebar.php"; ?>
