<?php include "sides/mininavi_3.php"; ?>
	<!-- Content -->
	<h1 style="text-align: center;">Eröffnungsrede von Frau Prof. Dr. Meyer zu Bexten</h1>
<p>Sehr geehrte Damen und Herren, liebe Kolleginnen und Kollegen, liebe Freunde!</p>
<p>Ich möchte Sie alle, und das natürlich auch im Namen meines Kollegen Herrn Prof. Schumann-Luck und meinen sehbehinderten und blinden Studenten, ganz herzlich hier begrüßen und mich für Ihr sehr zahlreiches Kommen aus den unterschiedlichsten Städten unserer Republik recht herzlich bedanken.</p>

<p>Als letzte Rednerin am heutigen Tag habe ich nun das schwere Los gezogen, Ihnen noch etwas Neues zu berichten, was zuvor noch nicht gesagt wurde. Meine Vorredner haben immer von dem Zentrum gesprochen, wie es derzeitig aufgebaut ist. Aber auch dieses Zentrum hat natürlich eine Vorgeschichte.</p>

<p>Als Gründerin vom BliZ, so lautet der Name unseres Zentrums für sehbehinderte und blinde Studierende, in der Hoffnung, derselbige möge uns nicht treffen, (höchstens als Geistesblitz), möchte ich die heutige Veranstaltung zum Anlaß nehmen und in meiner Rede zu Beginn einen Rückblick auf die letzten 13 Monate geben.</p>

<p>Ja, liebe Gäste, solange ist es nun schon wieder her, seit ich die erste Idee zu so einer Studienmöglichkeit für Blinde und Sehbehinderte hatte. Den einen mag zwar die Zeit kurz vorgekommen sein, denn in diesen 13 Monaten wurde sehr viel geschaffen. Den anderen wiederum kam die Zeit recht lang vor, da ich sie häufig mit vielen zusätzlichen Aufgaben und Problemen beschäftigt habe. Denke ich da beispielsweise an unsere Hausmannschaft.</p>

<p>Gerade in den letzten Wochen wurde ich immer wieder mit den folgenden Fragen konfrontiert:</p>
<p>- Welche Motivation hatten Sie, sich für behinderte Menschen, und speziell für Sehbehinderte und Blinde, zu engagieren?</p>
<p>und</p>
<p>- Wie sind Sie auf die Idee gekommen, ein solches Zentrum zu gründen?</p>

<p>Nun erst einmal zur ersten Frage:<br />Wie bin ich nun dazu gekommen, mich für Behinderte einzusetzen?</p>
<p>Vor vielen Jahren habe ich einmal einen Vortrag gehört, wo der Vortragende (ein Professor aus einer großen Uni-Klinik in den USA) seinen Vortrag unter das Motto stellte:</p>

<p>Jeder Mensch fühlt sich bzw. ist  in seinem Leben immer wieder einmal "behindert" !</p>

<p>Denken wir da doch beispielsweise mal an kleine Verletzungen, die wir uns im Alltagsleben zugezogen haben, z. B. wenn wir uns in den Finger geschnitten haben. Empfinden wir nicht dann schon bei solch kleinen Einschränkungen im Rahmen unserer Bewegungsfähigkeit diese als problematisch? Oder sei es, wenn wir mit einer Grippe krank im Bett liegen oder ähnliches. Wenn wir uns beobachten, merken wir, daß wir schon bei solch „kleinen Behinderungen“ anders reagieren, als unsere Mitmenschen es von uns erwarten. Vielleicht reagieren wir dann oft ungehalten und nervös, sehr zur Freude unserer Mitmenschen.</p>

<p>Leider gibt es nun viele Mitmenschen unter uns, die eine dauerhafte starke Behinderung haben. Schon ein kurzer Versuch, sich als nicht behinderter in ihre Lage zu versetzen, macht deutlich, wie sehr unsere technisierte Umwelt auf den Gebrauch aller Sinne und Fähigkeiten des gesunden und jugendlichen Menschen ausgerichtet ist.</p>
<p>Man sollte deshalb nicht aus den Augen verlieren, daß wir alle durch Unfall, Krankheit (was sich natürlich keiner wünscht), aber auch durch den natürlichen Alterungsprozess, den wir nun einmal nicht aufhalten können, eine Behinderung erleiden können.</p>

<p>Und sind wir nicht deshalb auch um unserer selbst Willen aufgefordert, Möglichkeiten anzubieten, um Behinderten zu helfen ?!</p>

<p>Der zuvor erwähnte Vortrag hat mich schon früh nachdenklich gemacht und motiviert, mich im Rahmen meiner Arbeit mit der Gestaltung von behindertengerechten Bildschirmarbeitsplätzen zu beschäftigen.</p>
<p>Bereits seit Ende der 80iger Jahre habe ich mich mit der Entwicklung behindertenkonformer ergonomischer grafischer Benutzeroberflächen in Kooperation mit Medizinern und Patienten beschäftigt.</p>
<p>Nun, als Professorin für praktische Informatik, habe ich mir zum Ziel gesetzt und auch dankenswerter Weise die Möglichkeit hier an der Hochschule bekommen, Sehbehinderten und Blinden bessere Studienmöglichkeiten anzubieten. Das hierbei der Schwerpunkt auf den Fächern Informatik und Wirtschaft liegt, hatte rein pragmatische Gründe.</p>
<p>Ziel muß und wird es in Zukunft sein, später unseren sehbehinderten und blinden Mitmenschen das Studium aller Fachrichtungen zu ermöglichen.</p>
<p>Die Gründung des Zentrums war dann für mich persönlich ein großer Schritt, der nicht so von Anfang an geplant war. Bei dessen Bewältigung, d. h. dem Übergang von der reinen Software-Entwicklung hin zur Gründung dieses Zentrums, gab es drei Ecksteine, die wesentlich dazu beigetragen haben, daß es zur Gründung des BliZ kam.</p>
<p>Wie bereits erwähnt, begann alles vor 13 Monaten, und zwar auf den Tag genau am 4. November 1997, als ich zu einem Treffen bei der IBM in Stuttgart eingeladen war. Dort traf ich zufällig Herrn Schneider, den dortigen Leiter des Beratungszentrums, Informationstechniken für Menschen mit Behinderungen, und wir sprachen über die verschiedenen technischen Unterstützungen für Behinderte. Bei unserem längeren Gespräch fragte mich Herr Schneider, warum ich mich nicht auch an der Fachhochschule Gießen-Friedberg, wie schon vorher an der Universität Dortmund, für Behinderte einsetze und Entwicklungen durchführen wolle. Bei unserem Gespräch kamen wir auch auf die Gruppe der Sehbehinderten und Blinden zu sprechen. Herr Schneider sagte mir dann gleich seine Unterstützung in Form von Soft- und Hardware im Bereich Sehgeschädigter für die Ausstattung von Arbeitsplätzen zu. Damit war für mich der erste Eckstein meines Gebäudes (Projektes) gelegt worden.</p>
<p>Nach meiner Rückkehr setzte ich mich dann mit der BLISTA, der Deutschen Blindenanstalt in Marburg in Verbindung, genauer gesagt mit Herrn Kalina und Herrn Sparenberg. Nach einigen Telefonaten und einem anschließenden Besuch bei Herrn Kalina an der BLISTA, wurde ich im Rahmen der Hochschulerkundungswoche am 29. Januar 1998 dorthin eingeladen und hatte dabei eine Gesprächsrunde mit mehreren Schülern. Darunter waren auch zwei unserer heutigen blinden Informatikstudenten, nämlich Herr Oschwald und Herr Sahin. In dieser Runde stellte ich unsere Fachhochschule vor, insbesondere natürlich auch den Studiengang Informatik. Ebenso präsentierte ich meine Planungen in Bezug auf die Studienunterstützung für die Sehbehinderten und Blinden. Herr Sahin und Herr Oschwald hat diese Gesprächsrunde wohl so sehr überzeugt, so daß sie mir zum Ende schließlich sagten:</p>
<p>Also, wenn sie so einen Studiengang Informatik für uns Blinde einrichten und (wir das Abitur schaffen ?), dann fangen wir zum nächsten Wintersemester an der Fachhochschule in Gießen an Informatik zu studieren</p>
<p>Am Ende dieser sehr interessanten Veranstaltung war ich nun noch mehr motiviert, ein spezielles Projekt für Sehbehinderte und Blinde ins Leben zu rufen. Und damit war der zweite Eckstein gelegt worden.</p>
<p>Nach weiteren Gesprächen an der Hochschule mit meinen Kollegen Herrn Prof. Kaufmann und Prof. Schumann-Luck erfuhr ich weitere Zustimmung. Gleiches galt auch für die Gespräche mit dem Präsidenten unserer Hochschule Herrn Prof. Kampschulte.</p>
<p>Trotz der vielen Zusprüche, die ich bis dato von verschiedenen Seiten erfahren hatte, war ich aber immer noch nicht hundertprozentig sicher, so ein großes Projekt durchführen zu können. Ich konnte zwar damals noch nicht die Dimension abschätzen, die das Zentrum heute angenommen hat, aber trotzdem sah ich immer noch mein Gebäude sehr wanken. Letztendlich gab mir mein Kollege Herr Prof. Lorenz Ende Februar den entscheidenden Anstoß und die notwendige Zuversicht zur Umsetzung meiner Ideen. Und damit war der dritte und letzte Eckstein für mein Gebäude (Projekt) gelegt.</p>
<p>An dieser Stelle möchte ich deshalb nochmals ganz herzlich allen, die ich zuvor genannt habe, für diese Unterstützung danken.</p>
<p>Nach meinem Beschluß nun für das Projekt begann die Phase der Realisierung, die sich in die beiden Bereiche Finanzierung und technische Planung des Zentrums teilte.</p>
<p>Leider kann ein solches Projekt nicht ohne finanzielle Mittel umgesetzt werden, ein Problem, was anfangs fast unüberwindlich schien. Desto mehr ich mich in mein Projekt vertiefte, merkte ich, was ich für die Grundausstattung alles benötigte und wie kostenintensiv diese Dinge alle waren.</p>
<p>Eine Basisfinanzierung für die Ausstattung des Zentrums wurde vom Rat der Hochschule genehmigt. Aber diese reichte längst nicht aus, um die notwendigsten Geräte usw. beschaffen zu können, so daß ich mich dann Anfang März des Jahres auf die Suche nach Sponsoren machte. Neben der Hochschule an sich hat einen weiteren großen Beitrag für die Einrichtung dieses Zentrum die Paul und Charlotte Kniese-Stiftung in Berlin geleistet, die für die Anschaffung der Braillezeilen mit zugehöriger Software gesorgt hat. Aber trotzdem hätte das Zentrum nicht in der heutigen Form aufgebaut werden können, hätte es nicht darüber hinaus die vielen, vielen anderen Sponsoren gegeben. Gesponsort wurden Softwaresysteme und Hardware, Monitore sowie komplette Rechneranlagen. Auch das Mobiliar vom Besprechungstisch mit Stühlen über Schränke und Regale hin zu höhenverstellbaren Schreibtischen wurde gespendet. Gleiches galt auch für die Ausstattung des Besprechungsraumes und der Teeküche.</p>
<p>Insgesamt habe ich für den Aufbau vom BliZ sage und schreibe an die 80 Sponsoren und Förderer gewinnen können.</p>
<p>Ihnen allen möchte ich an dieser Stelle nochmals meinen herzlichen Dank für Ihre tatkräftige Unterstützung aussprechen. Denn ohne Ihre starke finanzielle Unterstützung in Form von Geld- und Sachspenden und den vielen Ratschlägen und Hilfestellungen hätte ich diese Einrichtung nicht und erst gar nicht so schnell aufbauen können.</p>
<p>Denn damit waren die Steine, die zuvor nur langsam rollten, endlich nicht mehr aufzuhalten, und das Gebäude nahm immer mehr an Form an.</p>
<p>Bei der spezifischen Planung des Zentrums unterstützten mich nicht nur die beiden bereits an unserer Hochschule studierenden sehbehinderten Studenten Herr Öztürk und Herr Spellmeier, sondern auch meine verschiedenen Kooperationspartner, die ich inzwischen gewonnen hatte:</p>
<p>- BLISTA, Carl-Strehl-Schule (Herr Sparenberg (stellvertretende Schulleiter) und Herr Kalina (Informatiklehrer)). Frau Rausch, der Ausbildungsleiterin der Berufsschule für Datenverarbeitungs- und Informatikkaufleute.</p>
<p>- Herr Prof. Wünschmann von der Universität Dresden, Fakultät Informatik. Er lud mich nach Dresden ein und zeigte mir seine Einrichtung und gab mir viele wertvolle Hinweise und Unterstützung für das Zentrum.</p>
<p>- Universität Karlsruhe, Studienzentrum für Sehgeschädigte Herr Klaus besuchte mich hier an der Hochschule in den Anfängen der Planungsphase und gab mir auch viele wertvolle Ratschläge.</p>
<p>- Philipps-Universität Marburg<br />(Herr F.- J. Visse, ZAS / Beratung und Studienunterstützung Behinderter)</p>
<p>- DVBS (Deutscher Verein für Blinde und Sehbehinderte im Studium und Beruf), Marburg (Herr Jung, Geschäftsführer)</p>
<p>- Stiftung Blindenanstalt, Frankfurt a. Main (Frau Schwindling)</p>
<p>- Zentralstelle für Arbeitsvermittlung, Frankfurt am Main<br />(Herr Schwarzbach) Projekt Praktikantenbörse</p>
<p>Kommen wir nun zum Aufbau des Zentrums und einer kurzen Reise durch Zeit und Raum, denn ich möchte Ihnen eine kurze Übersicht über die geschichtliche Entwicklung präsentieren.</p>
<p>Die ersten Planungen sahen einen Raum in der Moltkestraße vor, einem Gebäude, was sich außerhalb des eigentlichen Fachhochschulgeländes befindet (grenzt an). Während der Planungsphase erhöhte sich der Raumbedarf aufgrund der notwendig gewordenen Einrichtung von 7 Arbeitsplätzen. Die Raumsuche konzentrierte sich mehr und mehr auf das C-Gebäude, da es sich aus verschiedenen Sichtweisen als geeignetstes Gebäude herauskristallisierte. Nachdem die Umbaumaßnahmen in der vorlesungsfreien Zeit im Sommer unter großem Zeitdruck durchgeführt wurden, konnte Ende August der Einzug des Blindenzentrums in die Räumlichkeiten in der 3. Etage des C-Gebäudes erfolgen. Ende Oktober wurde ein weiterer Raum in der dritten Etage bezogen und die Teeküche, aus der Sicht der Studenten die wichtigste Einrichtung überhaupt ?, eingerichtet werden.</p>
<p>Im Zentrum stehen damit den Studierenden zwei Computer-Arbeitsräume, ein Besprechungsraum und eine Teeküche zur Verfügung. Neben dem Zentrum liegt auch mein Büro, das auch immer wieder als Arbeits- und Besprechungsraum genutzt wird.</p>
<p>In der Zentralbibliothek wurde ein spezieller Bereich für die spezifischen Werke, also Bücher und CD's für die sehgeschädigten Studierenden, eingerichtet. Darüber hinaus kann durch Fernleihe auf weitere blinden- und sehbehindertengerechte Literatur von anderen Bibliotheken in der Bundesrepublik zurückgegriffen werden, die nicht in unserer eigenen Bibliothek vorhanden ist.</p>
<p>Außerdem habe ich sehr gute Beziehungen zu Verlagen aufbauen können, wie zum Beispiel zum Addison Wesley Verlag, Carl Hanser Verlag oder Heinz Heise Verlag, die mir ihre Bücher direkt in digitaler Form zur Verfügung stellten.</p>
<p>All Ihnen vielen herzlichen Dank dafür!!</p>
<p>In der Hoffnung, Sie nicht allzu sehr mit Details zu langweilen, möchte ich noch kurz über die technische Ausstattung der beiden Computer-Arbeitsräume berichten.</p>
<p>In den beiden Computer-Arbeitsräumen wird den Sehbehinderten und Blinden spezielle technologische Infrastruktur in Kombination mit verschiedenen modernen Informationstechnologien zur Verfügung gestellt. Durch die Anschaffung dieser speziellen Hardware und Software wird ihnen trotz ihrer Behinderung ein effizienter Umgang mit dem zur Verfügung stehenden Datenmaterial gewährleistet und der Zugang zu den studienrelevanten Informationen ermöglicht, was erheblich zum Nachteilsausgleich gegenüber ihren nicht behinderten Kommilitonen beiträgt.</p>
<p>Diese Arbeitsräume sind wie folgt ausgestattet.</p>
<p>Wir haben dort</p>
<p>- sechs verschiedene Rechner mit in Größe und Art unterschiedlichen Monitoren, dazu noch zwei Notebooks für das Arbeiten unterwegs oder für Präsentationen außerhalb der FH.</p>
<p>- Dazu besitzen wir 3 Brailleausgabezeilen und 2 Bildschirmlesegeräte.</p>
<p>- Des weiteren haben wir 2 Scanner, womit wir in der Lage sind, auch umfangreiches Druckmaterial fast automatisch in digitale Form zu bringen.</p>
<p>- Für die Ausgabe unserer Arbeitsergebnisse besitzen wir neben einem Laser- und einem Farb-Tintenstrahldrucker auch einen doppelseitig druckenden Brailledrucker. Für Grafiken besitzen wir zudem noch einen taktilen Drucker.</p>
<p>- Die Ausstattung unseres Labors wird vervollständigt durch einen sehr komfortablen Kopierer.</p>
<p>- Zum Austausch von Daten und Informationen wurde uns eine komplette Kommunikationseinrichtung vom Telefon über Fax bis hin zum Videokonferenzsystem zur Verfügung  gestellt.</p>
<p>- Außerdem haben wir zur Dokumentation unserer Arbeit und zum Trainieren von Gesprächs- und Vortragssituationen eine komplette Video-Ausrüstung.</p>
<p>- Neben der Hardware haben wir Softwaresysteme für die Sprachausgabe, Texterkennung und Bildvergrößerung.</p>
<p>Doch nun habe ich Sie mit Details genügend überhäuft und ich würde sagen, wir schauen uns UNSER GEMEINSAMES PROJEKT, DAS BLIZ, einfach gleich einmal zusammen an.</p>

	<!-- ContentEnde -->
<?php include "sides/fachbereich/profilsidebar.php"; ?>
