<?php include "sides/mininavi_3.php"; ?>
	<!-- Content -->
	<h1>Preisverleihung "Wissenschaft ohne Barrieren"</h1>
<p>Unsere Arbeit wird belohnt. Das Equal Newsletter (Ausgabe 5 2008) berichtete über die Preisverleihung "Wissenschaft ohne Barrieren". Hier sehen Sie den Originaltext des Newsletters.</p>
<p style="text-align: center;">----------------------------------------------------------------</p>
<p>Mit einem repräsentativen Höhepunkt ging das EQUAL-Projekt "Vieles ist möglich – Tandem-Partner in der Wissenschaft" im November 2007 zu Ende. Im Rahmen einer bundesweiten Veranstaltung in der Akademie der Wissenschaften wurden von der Parlamentarischen Staatssekretärin im Bundesministerium für Gesundheit, Marion Caspers-Merk, in Berlin drei Institutionen geehrt, die sich in besonderer Weise um die Integration von Menschen mit Behinderungen in Wissenschaft und Forschung verdient gemacht haben.</p>
<p>In seinem Grußwort ermöglichte der Präsident des Paul-Ehrlich-Instituts, Prof. Dr. Johannes Löwer, den Gästen zu Beginn noch einmal einen Rückblick auf die Anfänge des Tandem-Projektes: "Mit dem Modell der Tandem-Partnerschaften hat sich das Paul-Ehrlich-Institut erstmals 1996 für die Integration von Menschen mit Behinderungen in das wissenschaftliche Arbeitsleben eingesetzt", erläuterte er. Diese Maßnahme konnte bis 2004 von zunächst sechs ABM-Projekten mit elf Beschäftigten auf insgesamt 34 Arbeitsverhältnisse erweitert werden. 2005 haben wir uns entschlossen, die Integration von Menschen mit Behinderungen in einem europäischen Projekt voran zu bringen, und wir können heute auf drei Jahre sehr erfolgreicher Arbeit zurückblicken".</p>
<p>Von der Fernsehmoderatorin Bettina Eistel moderiert und dem Tenor der Frankfurter Oper, Izet Salihi, musikalisch begleitet, wurde allen Projektbeteiligten und Gästen ein würdigerRahmen geboten, der die eigentlichen Akteure des Projektes, nämlich die Menschen mit Behinderungen und ihre Fähigkeiten, noch einmal in den Mittelpunkt des Interesses rückte. So zum Beispiel bei der offiziellen Preisverleihung, bei der die drei Preisträger im feierlichen Rahmen einen von der Entwicklungspartnerschaft ausgelobten Integrationspreis in Form eines Geldpreises und einer Skulptur überreicht bekamen.</p>
<h2>Die Preisträger des Integrationspreises</h2>
<p>Der dritte Preis des Integrations­preises "Wissenschaft ohne Barrieren" ist mit 10 000 EURO dotiert und geht an die Fachhochschule für Technik und Wirtschaft Berlin (FHTW) und der Zweite Preis geht an das Zentrum für Disability Stu­dies – ZeDiS an der Universität Hamburg.</p>
<p> </p>
<img src="images/equal-newsletter-5-1.jpg" alt="Die Preisträger/innen mit der Moderatorin Bettina Eistel und dem Projektleiter Klaus Posselt" title="Die Preisträger/innen mit der Moderatorin Bettina Eistel und dem Projektleiter Klaus Posselt" width="600" height="228" /><br /><em>Die Preisträger/innen mit der Moderatorin Bettina Eistel (2. v. r.) und dem Projektleiter Klaus Posselt (l. h.)</em>
<h2></h2>
<h2><strong>Laudationes der Staatssekretärin Marion Caspers-Merk</strong></h2>
<img alt="Prof. Dr. E. Meyer zu Bexten mit dem Integrationspreis" title="Prof. Dr. E. Meyer zu Bexten mit dem Integrationspreis" src="images/equal-newsletter-5-2.jpg" style="float: left; margin-right: 10px; margin-bottom: 10px;" width="356" height="332" />
<p>Der Erste Preis des Integrationspreises "Wissenschaft ohne Barrieren" ist mit 15.000 Euro dotiert und geht an das Zentrum für blinde und sehbehinderte Studierende - BliZ - an der Fachhochschule Gießen-Friedberg.<br /><br />Das BliZ ermöglicht blinden und sehbehinderten Menschen durch ganz gezielte Betreuung und Unterstützung ein reguläres Studium an der FH Gießen-Friedberg. Seit seiner Gründung vor fast 10 Jahren ist das Zentrum stetig gewachsen. Heute betreut es 35 sehbehinderte Studierende -angehende Betriebswirte und Informatiker, aber auch Ingenieure, und bietet darüber hinaus sechs Ausbildungsplätze für sehgeschädigte Jugendliche. Mit einem ganzen Bündel von Maßnahmen sorgt das Angebot dafür, dass sehbehinderte und blinde Studierende dieselbe Ausbildung absolvieren können wie alle anderen Studierenden der Fachhochschule.</p>
<p style="clear: left;">Das beginnt schon beim Studieneinstieg, den das BliZ durch Informations­ und Orientierungstage, aber auch mit individuellen Beratungen und Mobilitätstrainings unterstützt. Ist der Einstieg ins Studium geschafft, setzt es sich dann für den Nachteilsausgleich für sehgeschädigte Studierende ein. Dazu stellt das BliZ Räume, aber auch vielfältige Hilfsmittel zur Verfügung. Außerdem bereitet es Lehrmittel so auf, dass diese auch von blinden Studierenden genutzt werden können. Schließlich sorgt das BliZ auch dafür, dass Klausuren und andere Leistungsnachweise unter behinderungsgerechten Rahmenbedingungen erbracht werden können. Über das Studium hinaus hilft das BliZ sehgeschädigten Studierenden auch bei der Organisation von Praktika - und nach dem erfolgreichen Ende des Studiums bei der Suche nach einem Arbeitsplatz. Beide Prozesse finden in sehr enger Kooperation mit der Agentur für Arbeit, aber auch mit den potentiellen Arbeitgebern statt, denen das Zentrum mit seinem "Know-how" immer zur Verfügung steht.</p>
<br /> <img src="images/equal-newsletter-5-3.jpg" alt="Mitarbeiter des BliZ an verschiedenen Hilfsmittel-Arbeitsplätzen" title="Mitarbeiter des BliZ an verschiedenen Hilfsmittel-Arbeitsplätzen" width="600" height="145" />
<p>Durch seine Beharrlichkeit und den großen Einsatz hat das BliZ in den vergangenen Jahren dafür gesorgt, dass sehgeschädigten und blinden Menschen ganz neue, hochqualifizierte Berufsfelder offenstehen. Das ist eine bedeutende Errungenschaft, die ohne die großartige Tätigkeit des BliZ gar nicht möglich gewesen wäre.</p>
<p>Dafür darf ich Frau Professor Meyer zu Bexten, die das Zentrum vor fast 10 Jahren initiiert hat und es bis heute mit viel Engagement leitet, stellvertretend für das ganze Zentrum heute den 1. Preis überreichen.</p>
	<!-- ContentEnde -->
<?php include "sides/fachbereich/profilsidebar.php"; ?>
